### ISSUE TITLE
Using build-dev.sh sometimes throws network errors

### ISSUE THREAD

**Issue by xadahiya** [PowerLoom/deploy#15]
## Describe the bug 
Stopping and Starting services using `./build-dev.sh` occasionally throws Error
```Error response from daemon: network 07cecd2548b6251645426f6236e68841d180c8e87a9ff12a8d65beb994d11123 not found```

## To Reproduce

1. Start all services using `./build-dev.sh` 
2. Stop them using `docker-compose down --volumes`
3. Repeat 1 and 2

**Expected behavior**
All services should start and stop without any issues

**Proposed Solution**
Enabling `--force-recreate` flag in `build-dev.sh` startup command should fix the issue.

**Additional context**
Observed in Mac OS Ventura (Apple Silicon)

**Comment by SwaroopH** [comment]
Ran into it with build.sh setup today. The best way to cleanup is to prune docker and restart to fix it.

**Comment by SwaroopH** [comment]
Looks like doing a `down` without specifying the profile is also a culprit. This is the right command:

`docker-compose --profile ipfs down --volumes`

**Comment by SwaroopH** [comment]
Above is for `./build.sh`. For `build-dev` it's:

`docker-compose -f docker-compose-dev.yaml --profile ipfs --profile consensus down --volumes`
