### ISSUE TITLE
env.example in feat/proto_snapshot_collector branch missing slot ID

### ISSUE THREAD

**Issue by anomit** [PowerLoom/deploy#40]
## Describe the bug 
Issue title is self-explanatory

## To Reproduce
**Affected versions**:

1. run `./bootstrap.sh` 
2. run `./build-dev.sh` 

**Expected behavior**
the env example should include slot ID. This will cause the `.env` load to further pass the slot ID to pooler initialization scripts.

**Proposed Solution**
include slot ID in env example

**Caveats**
NA

**Additional context**
Ensure the correct images of `pooler` and `audit-protocol` are pulled that utilize the slot ID.

**Comment by muku314115** [comment]
will be taken in the current iteration

**Comment by muku314115** [comment]
Wasn't taken up due to higher priority tasks, will be updated soon

**Comment by anomit** [comment]
Snapshotter V2 full nodes will require its own deploy repository with a new env file template where this will be applicable. We are not using the older `deploy` repo any more for V2 full nodes.
